name: Merge
author: Guillaume Clochard <guillaume.clochard@iadvize.com>
description: Use this actions to merge pull requests that are ready after a check_suite completed

inputs:
  token:
    description: A Github token.
    required: true

  label:
    description: 'Only merge pull requests with this label'
    required: false

  shouldDeleteBranch:
    description: 'Should we delete the branch after merge?'
    required: false
    default: true

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'orange'
  icon: 'git-merge'
