name: Issue comment
author: Guillaume Clochard <guillaume.clochard@iadvize.com>
description: Use this actions to add a comment on an issue or pull request

inputs:
  issue_number:
    description: The issue/PR number to comment on.
    required: true

  token:
    description: A Github token.
    required: true

  comment:
    description: The comment.
    required: true

  repository:
    description: >
      The repository to find the issue/PR to comment on.
      Default to <owner/repo> of the current workflow.
    required: false

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'gray-dark'
  icon: 'message-circle'
