name: Build actions on release branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    name: 'Build Javascript actions'

    steps:
      - name: 'Checkout directory'
        uses: actions/checkout@v1

      - name: 'Init Git name'
        run: |
          git config --global user.name "iadvize/actions Build JS actions workflow"
          git config --global user.email "github-workflow@iadvize.com"

      - name: 'Copy script'
        run: cp .github/build-javascript-actions.sh /tmp/build-javascript-actions.sh

      - name: 'Checkout release branch'
        run: git checkout release

      - name: 'Merge master on release'
        run : git merge origin/master --ff

      - name: 'Build Javascript actions'
        run: /tmp/build-javascript-actions.sh

      - name: 'Commit and push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -n "$(git status --porcelain)" ]; then
            echo "Nothing to commit. Done.";
            exit 0;
          fi

          authenticatedUrl="https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote set-url origin $authenticatedUrl

          git add .
          git commit -m "Built Javascript actions"

          git push

