name: 'Welcome Pull Requests'

on: pull_request

jobs:

  comment:
    runs-on: ubuntu-18.04

    name: 'Comment with release branch'

    steps:
      - name: 'Build comment message'
        id: buildMessage
        env:
          branch: ${{ github.event.head_ref }}
        run: |
          message='Hello! You can find the temporary released actions in the `'release-$branch'` branch'
          echo "##[set-output name=message;]$message"

      - name: 'Comment on PR'
        uses: iadvize/actions/issue-comment@d25c66574f9e233663f1bb0e7efa70628abc12ea
        # if: github.event.action == 'opened'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.number }}
          comment: ${{ steps.buildMessage.message }}

